# Generated by Django 3.1.7 on 2022-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unicornuser',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
