# Generated by Django 4.0.4 on 2022-05-07 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0002_alter_community_image_alter_griefimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpvoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_id', to='unicorn.comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='unicorn.user')),
            ],
        ),
    ]
