# Generated by Django 3.2 on 2022-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0002_alter_userprofile_grief_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/resources'),
        ),
        migrations.AddField(
            model_name='unicornuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'UnicornAdmin'), (2, 'Griever')], null=True),
        ),
    ]
