# Generated by Django 3.2 on 2022-05-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0004_resources_resource_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_community', to='unicorn.community'),
        ),
    ]
