# Generated by Django 3.2 on 2022-05-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0005_userprofile_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='griefstage',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
