# Generated by Django 3.2 on 2022-05-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0006_griefstage_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='grief_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_grief_stage', to='unicorn.griefstage'),
        ),
        migrations.AlterField(
            model_name='community',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
