# Generated by Django 3.2 on 2022-05-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0008_alter_community_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='grief_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_grief_stage', to='unicorn.griefstage'),
        ),
    ]
