# Generated by Django 3.2 on 2022-05-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0010_alter_community_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grief_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_grief_stage', to='unicorn.griefstage'),
        ),
    ]
