# Generated by Django 3.2 on 2022-05-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0011_alter_userprofile_grief_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='resource_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='community',
            name='grief_stage',
        ),
        migrations.RemoveField(
            model_name='community',
            name='image',
        ),
        migrations.RemoveField(
            model_name='community',
            name='population',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='grief_stage',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='community',
        ),
        migrations.AddField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
