# Generated by Django 3.2 on 2022-05-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0013_auto_20220515_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicornuser',
            name='username',
            field=models.CharField(max_length=23),
        ),
    ]
