# Generated by Django 3.2 on 2022-05-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0014_alter_unicornuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unicornuser',
            name='email_verified',
        ),
    ]
